### ISSUE TITLE
Spanish support

### ISSUE THREAD

**Issue by oyes77** [dominikmayer/obsidian-yesterday#1]
"Speakers denoted with `me`, `ich`, `moi`, `yo`, `我`, … will be shown on the right side. (Create an [[issue](https://github.com/dominikmayer/obsidian-yesterday/issues)](https://github.com/dominikmayer/obsidian-yesterday/issues) if your language is not yet supported.)"

I'd like for spanish to be supported, is there a way to contribute?

**Comment by dominikmayer** [comment]
Hi, thanks for reaching out.

Plugins cannot be localized so all we can do is support Spanish in dialogs. According to ChatGPT you would use "yo" for "me" and that should be supported. Does it not work for you or is it the wrong word?
