### ISSUE TITLE
Contact information

### ISSUE THREAD

**Issue by dxcore35** [dominikmayer/obsidian-yesterday#2]
Hello I would like to ask more about beta testing of the app. But I cannot find email contact.

**Comment by dominikmayer** [comment]
Hi, please use the form at [www.mitado.com](https://www.mitado.com/contact/). Thank you.

**Comment by dxcore35** [comment]
I tried to contact you here, but I dont understand even this is correct website as you are asking question about budget I have no budget and im not company. And I dont know your company has any relation to this sofware. I expect you are some indie freelance developer and I will find your personal email.

**Comment by dominikmayer** [comment]
Yes, it's the correct website. There's even a link on the [app page](https://mitado.notion.site/iOS-macOS-App-cb76c8cec9b041c29271cc23d1bbff8a).

You can select whatever budget.
