### ISSUE TITLE
Allow for custom parent folder

### ISSUE THREAD

**Issue by SteffoSpieler** [dominikmayer/obsidian-yesterday#5]
The default is for the plugin to create the 2000s folder directly at the top of the vault.

I'd love to have a setting to change it so that the automatic files / folders are created in e.g. `Journal` / `Diary` / `Something in another language, as why it's custom`.

**Comment by dominikmayer** [comment]
Hi, thanks for the suggestion. I added support for this.

**Comment by dominikmayer** [comment]
Closing
